project_name: gnt

release:
  prerelease: auto
  draft: true # I'm taking a look at the release draft, editing and publishing
  name_template: "gnt v{{ .Version }}"

builds:
  - id: linux # Build for Linux
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    binary: bin/gnt
    main: ./cmd/gnt/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X go.szostok.io/version.version={{.Version}}
      - -X go.szostok.io/version.buildDate={{.Date}}
  - id: macos # Build for macOS
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    binary: bin/gnt
    main: ./cmd/gnt/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X go.szostok.io/version.version={{.Version}}
      - -X go.szostok.io/version.buildDate={{.Date}}

archives:
  - id: linux_archive
    builds:
      - linux
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - VERSION
      - docs/CHANGELOG.md
  - id: macos_archive
    builds:
      - macos
    format: zip
    files:
      - LICENSE
      - README.md
      - VERSION
      - docs/CHANGELOG.md

brews:
  -
    name: gnt
    homepage: https://github.com/lnxwizard/gnt
    description: "Easily create your Go projects in the terminal."
    license: "MIT"
    tap:
      owner: lnxwizard
      name: homebrew-gnt
    commit_author:
      name: lnxwizard
      email: alperakca79@outlook.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
